site_name: DeeP-LCC
site_author: Haoxing Du, Meihui Liu, Yang Zheng

# Repository
repo_name: soc-ucsd/DeeP-LCC
repo_url: https://github.com/soc-ucsd/DeeP-LCC
edit_uri: edit/main/docs

# Copyright
copyright: Copyright &copy; 2022 SOC Lab

nav:
    - Welcome: index.md
    - DeeP-LCC: deepLCC.md
    

extra_javascript:
  - javascripts/katex.js 
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - toc:
      permalink: true
  - md_in_html
  - mdx_math


# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.tracking
    - navigation.indexes
    - toc.integrate 
    - toc.follow
    - navigation.expand
  language: en
  icon:
    repo: fontawesome/brands/github
    
  palette:
      # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
    
plugins:
   - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       skip_classes: 
         - custom-skip-class-name
       auto_caption: false
       caption_position: bottom
